### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: format.numpy.foo.FooException.InternalFoo
  fullName: format.numpy.foo.FooException.InternalFoo
  inheritance:
  - type: builtins.object
  langs:
  - python
  module: format.numpy.foo.FooException
  name: InternalFoo
  source:
    id: InternalFoo
    path: D:Github\python2yaml\tests\example\format\numpy\foo.py
    remote:
      branch: develop
      path: D:Github\python2yaml\tests\example\format\numpy\foo.py
      repo: https://github.com/docascode/python2yaml.git
    startLine: 186
  summary: 'Docstring of internal class :class:`format.numpy.foo.FooException.InternalFoo`.

    This class is an internal class of :class:`format.numpy.foo.FooException`.'
  type: class
  uid: format.numpy.foo.FooException.InternalFoo
references: []
